# docs: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on: [push]

jobs:
  # stages
  build:
    # runtime environment
    runs-on: ubuntu-latest
    
    # jobs
    steps:
    # checkout
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    # prepare environment
    - name: Prepare Environment
      run: |
        curl https://raw.githubusercontent.com/EnvCLI/modular-pipeline/master/install.sh | sudo sh
    # pipeline steps
    - name: Test
      run: |
        go-test
    - name: Build
      run: |
        go-build
    - name: Optimize
      run: |
        optimize-upx
    - name: Publish
      env:
        BINTRAY_ORGANZATION: envcli
        BINTRAY_REPOSITORY: golang
        BINTRAY_PACKAGE: normalize-ci
        BINTRAY_USERNAME: philippheuer
        BINTRAY_TOKEN: ${{ secrets.BINTRAY_TOKEN }}
      run: |
        bintray-publish
