# workflow
name: CI

# trigger
on:
  push:
    # Push events on master branch
    branches:    
      - master

# jobs
jobs:
  # stages
  build:
    # runtime environment
    runs-on: ubuntu-latest
    
    # jobs
    steps:
    # checkout
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    # prepare environment
    - name: Environment Setup
      run: |
        curl https://raw.githubusercontent.com/EnvCLI/modular-pipeline/master/install.sh | sudo bash
    # pipeline steps
    - name: Prepare
      env:
        PROJECT_TYPE: golang-cli
      run: |
        stage-prepare
    - name: Build
      env:
        PROJECT_TYPE: golang-cli
      run: |
        stage-build
    - name: Test
      env:
        PROJECT_TYPE: golang-cli
      run: |
        stage-test
    - name: Package
      env:
        PROJECT_TYPE: golang-cli
      run: |
        stage-package
    - name: Audit
      env:
        PROJECT_TYPE: golang-cli
      run: |
        stage-audit
    - name: Deploy
      env:
        PROJECT_TYPE: golang-cli
      run: |
        stage-deploy production
    - name: Performance
      env:
        PROJECT_TYPE: golang-cli
      run: |
        stage-performance
    - name: CleanUp
      env:
        PROJECT_TYPE: golang-cli
      run: |
        stage-cleanup
