# workflow
name: CI

# trigger
on:
  push:
    # Push events on master branch
    branches:    
      - master

# jobs
jobs:
  # stages
  build:
    # runtime environment
    runs-on: ubuntu-latest
    
    # jobs
    steps:
    # checkout
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    # prepare environment
    - name: Environment Setup
      run: |
        curl https://raw.githubusercontent.com/EnvCLI/modular-pipeline/master/install.sh | sudo bash
        export PROJECT_TYPE=golang-cli
    # pipeline steps
    - name: Prepare
      run: |
        stage-prepare
    - name: Build
      run: |
        stage-build
    - name: Test
      run: |
        stage-test
    - name: Package
      run: |
        stage-package
    - name: Audit
      run: |
        stage-audit
    - name: Deploy
      run: |
        stage-deploy
    - name: Performance
      run: |
        stage-performance
    - name: CleanUp
      run: |
        stage-cleanup
