# workflow
name: CI

# trigger
on:
  push:
    # Push events on master branch
    branches:    
      - master

# jobs
jobs:
  # stages
  build:
    # runtime environment
    runs-on: ubuntu-latest
    
    # jobs
    steps:
    # checkout
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    # prepare environment
    - name: Environment Setup
      run: |
        curl -L -s https://raw.githubusercontent.com/EnvCLI/modular-pipeline/master/install-prerequisites.sh | sudo bash -s
        curl -L -s https://raw.githubusercontent.com/EnvCLI/modular-pipeline/master/install.sh | sudo bash -s /usr/local
    # pipeline steps
    - name: Prepare
      run: |
        mpi stage prepare
    - name: Build
      run: |
        mpi stage build
    - name: Test
      run: |
        mpi stage test
    - name: Package
      run: |
        mpi stage package
    - name: Audit
      run: |
        mpi stage audit
    - name: Performance
      run: |
        mpi stage performance
    - name: CleanUp
      run: |
        mpi stage cleanup
