# workflow
name: Release

# trigger
on:
  push:
    tags:        
      - v*

# jobs
jobs:
  # stages
  build:
    # runtime environment
    runs-on: ubuntu-latest

    # jobs
    steps:
    # checkout
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    # prepare environment
    - name: Environment Setup
      run: |
        curl https://raw.githubusercontent.com/EnvCLI/modular-pipeline/master/install.sh | sudo bash
    # pipeline steps
    - name: Prepare
      run: |
        stage-prepare
    - name: Build
      env:
        UPX_ENABLE: "true"
        UPX_ARGS: --brute
      run: |
        stage-build
    - name: Test
      run: |
        stage-test
    - name: Package
      run: |
        stage-package
    - name: Publish
      env:
        BINTRAY_ORGANZATION: envcli
        BINTRAY_REPOSITORY: golang
        BINTRAY_PACKAGE: normalize-ci
        BINTRAY_USERNAME: philippheuer
        BINTRAY_TOKEN: ${{ secrets.BINTRAY_TOKEN }}
      run: |
        stage-publish
    - name: Audit
      run: |
        stage-audit
    - name: Performance
      run: |
        stage-performance
    - name: CleanUp
      run: |
        stage-cleanup
